#!/bin/bash

MPOINT="./mount-point"

rm -R -f test
mkdir test

#1

cp ./src/fuseLib.c ./temp/filea.txt
cp ./temp/filea.txt $MPOINT/
#echo ./src/fuseLib.c > ./temp/filea.txt
cp ./src/myFS.h ./temp/fileb.txt
cp ./temp/fileb.txt $MPOINT/
#echo ./src/myFS.h > ./temp/fileb.txt

#2

./my-fsck 
diff fuseLib.c filea.txt
diff myFS.h fileb.txt

#3

 
